version: '3.8'

services:
  app:
    build: .
    container_name: devops-login-app
    restart: always
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=production_jwt_secret_devops_aws_2026
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
    driver: local
